name: CI Java App
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Build The App
        run: "mvn clean package"
        shell: bash

      - name: Test The App
        run: "mvn test"
        shell: bash

