name: CI Java App2
on:
    workflow_dispatch:
      inputs:
        versionName:
          required: true
          description: "This is version for github workflow"



    # repository_dispatch:
    #   types: [test]
    # push:
    #     branches:
    #         - "master"         
jobs:
    build:
        name: Build and Package Java App
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Build and Packagen
              run: mvn clean package

   